config_lock_expiry_seconds: 120
config_lock_poll_interval: 5
config_lock_timeout: 150
db_name: dev
derived_aem_pack_topic: derived-aempacks
generate_correlation_id: true
kafka_compression_type: null
kafka_dlq_topic: dlq
kafka_enable_dlq: true
kafka_max_message_size: 1048576
kafka_max_retries: 0
kafka_retry_backoff: 0
kafka_security_protocol: PLAINTEXT
kafka_servers:
- kafka:9092
kafka_ssl_cafile: ''
kafka_ssl_certfile: ''
kafka_ssl_keyfile: ''
kafka_ssl_password: ''
log_format: null
log_level: INFO
log_traceback: true
mongo_dsn: '**********'
mongo_timeout: null
original_aem_pack_topic: original-aempacks
processing_configuration_path: input_dummy.yaml
processing_poll_pause: 60
service_instance_id: '1'
service_name: ets
worker_id: test-worker
