components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
      type: object
info:
  description: A minimal mock service passing the workflow id to application layer
  title: EM Transformation Service
  version: 0.1.0
openapi: 3.1.0
paths:
  /health:
    get:
      description: Test endpoint to check if the service is running.
      operationId: health_check_health_get
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Health check endpoint
  /workflows:
    post:
      description: Submit a workflow for execution.
      operationId: submit_workflow_workflows_post
      parameters:
      - in: query
        name: workflow_id
        required: true
        schema:
          title: Workflow Id
          type: string
      responses:
        '201':
          content:
            application/json:
              schema:
                title: Response Submit Workflow Workflows Post
                type: string
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Submit a workflow id for execution
servers:
- url: ''
