# Please only mention the non-default settings here:

service_instance_id: "1"
kafka_servers: ["kafka:9092"]
mongo_dsn: "mongodb://mongodb:27017"
db_name: "dev"
kafka_enable_dlq: True
processing_definition_path: input_dummy.yaml
original_aem_pack_topic: original-aempacks
derived_aem_pack_topic: derived-aempacks
worker_id: test-worker
